#!/usr/bin/bash
# script that will display information about subdomains.


domain="$1"
subdomain="$2"
get_dns_info() {
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        dns_info=$(dig +short "$sub.$domain")

        record_type=$(echo "$dns_info" | awk '{if ($1 == "CNAME") print "CNAME"; else print "A"}')
        destination=$(echo "$dns_info" | awk '{if ($1 == "CNAME") print $2; else print $1}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    
    done
}

get_dns_info "$domain" "$subdomain"

