#!/usr/bin/env bash
# This script is read usind IFS

while IFS=':' read -r USERNAME PASSWORD GROUP_ID USER_ID USER HOME_DIRECTORY COMMAND
do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER "
done < /etc/passwd
