#!/usr/bin/env bash
## This script is displaying a clock from 0 to 12

hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -lt 60 ]
    do
        echo "$minute" 
        ((minute+=1))
    done
    ((hour+=1))  
done
