#!/usr/bin/env bash
# Script to reload gunicorn gracefully

for pid in $(ps aux | grep 'gunicorn --workers' | grep -v grep | awk '{print $2}'); do
    echo "Reloading Gunicorn worker: $pid"
    kill -HUP $pid
done
